classdef TestPersistence < io.mpa.Persistence
    
    enumeration
        
        COMPUND_ENTITY_DS([...
            io.mpa.H5DataType.COMPOUND_INTEGER_DATASET.map('integers') ...
            io.mpa.H5DataType.COMPOUND_STRING_DATASET.map('strings') ...
            io.mpa.H5DataType.COMPOUND_DOUBLE_DATASET.map('doubles') ...
            ])
        
        COMPUND_ENTITY_ATTR([...
            io.mpa.H5DataType.COMPOUND_INTEGER_ATTR.map('integers') ...
            io.mpa.H5DataType.COMPOUND_STRING_ATTR.map('strings') ...
            io.mpa.H5DataType.COMPOUND_DOUBLE_ATTR.map('doubles') ...
            ])
    end
end
