classdef TestSchema < io.mpa.Schema
    
    enumeration
        
        COMPUND_ENTITY_DS([...
            io.mpa.H5DataType.COMPOUND_INTEGER_DATASET.map('integers') ...
            io.mpa.H5DataType.COMPOUND_STRING_DATASET.map('strings') ...
            io.mpa.H5DataType.COMPOUND_DOUBLE_DATASET.map('doubles') ...
            ])
        
        COMPUND_ENTITY_ATTR([...
            io.mpa.H5DataType.COMPOUND_INTEGER_ATTR.map('integers') ...
            io.mpa.H5DataType.COMPOUND_STRING_ATTR.map('strings') ...
            io.mpa.H5DataType.COMPOUND_DOUBLE_ATTR.map('doubles') ...
            ])

        SIMPLE_ENTITY_ATTR([...
            io.mpa.H5DataType.SIMPLE_INTEGER_ATTR.map('integer') ...
            io.mpa.H5DataType.SIMPLE_STRING_ATTR.map('string') ...
            io.mpa.H5DataType.SIMPLE_DOUBLE_ATTR.map('double') ...
            ])

        COMPLEX_ENTITY([...
            io.mpa.H5DataType.COMPOUND_INTEGER_DATASET.map('integersDs') ...
            io.mpa.H5DataType.COMPOUND_STRING_DATASET.map('stringsDs') ...
            io.mpa.H5DataType.COMPOUND_DOUBLE_DATASET.map('doublesDs') ...
            io.mpa.H5DataType.COMPOUND_INTEGER_ATTR.map('integersAttr') ...
            io.mpa.H5DataType.COMPOUND_STRING_ATTR.map('stringsAttr') ...
            io.mpa.H5DataType.COMPOUND_DOUBLE_ATTR.map('doublesAttr') ...
            io.mpa.H5DataType.SIMPLE_INTEGER_ATTR.map('integer') ...
            io.mpa.H5DataType.SIMPLE_STRING_ATTR.map('string') ...
            io.mpa.H5DataType.SIMPLE_DOUBLE_ATTR.map('double') ...
            io.mpa.H5DataType.COMPOUND_DOUBLE_DATASET.map('struct') ...
            io.mpa.H5DataType.SIMPLE_STRING_ATTR.map('dynamicSchema') ...
            ])
    end
end
